from __future__ import annotations

from copy import deepcopy


PROFILES = {
    "epson_1_0": {
        "id": "epson_1_0",
        "name": "Epson PJLink 1.0",
        "brand": "Epson",
        "pjlink_class": 1,
        "default_auth_mode": "none",
        "power_on_delay": 2.0,
        "power_off_delay": 2.0,
        "supports": {
            "freeze": False,
            "speaker_volume": False,
            "microphone_volume": False,
            "input_name": False,
            "input_resolution": False,
            "recommended_resolution": False,
            "filter_hours": False,
            "lamp_model": False,
            "filter_model": False,
            "serial_number": False,
            "software_version": False,
        },
        "inputs": {
            "11": "Computer 1",
            "12": "Computer 2",
            "21": "Video",
            "31": "HDMI 1",
            "32": "HDMI 2",
        },
        "manufacturer_name": "EPSON",
        "product_name": "EB-L530U Simulator",
        "device_name": "EPSON-SIM",
        "other_info": "Class 1 compatibility profile for regression testing",
        "lamp_models": [],
        "filter_models": [],
        "lamp_hours": [812],
        "filter_hours": [],
        "serial_number": "",
        "software_version": "",
        "input_resolution": "",
        "recommended_resolution": "",
        "error_status": "000000",
    },
    "smile_2_0": {
        "id": "smile_2_0",
        "name": "Smile 2.0",
        "brand": "Smile",
        "pjlink_class": 2,
        "default_auth_mode": "md5",
        "power_on_delay": 1.5,
        "power_off_delay": 1.5,
        "supports": {
            "freeze": True,
            "speaker_volume": True,
            "microphone_volume": True,
            "input_name": True,
            "input_resolution": True,
            "recommended_resolution": True,
            "filter_hours": True,
            "lamp_model": True,
            "filter_model": True,
            "serial_number": True,
            "software_version": True,
        },
        "inputs": {
            "11": "PC",
            "12": "VGA",
            "31": "HDMI 1",
            "32": "HDMI 2",
            "33": "DisplayPort",
            "34": "DVI",
        },
        "manufacturer_name": "SMILE",
        "product_name": "SMILE-EK Simulator",
        "device_name": "SMILE-SIM",
        "other_info": "Class 2 profile with freeze, volume and extended info",
        "lamp_models": ["SMILE-LAMP-01"],
        "filter_models": ["SMILE-FILTER-01"],
        "lamp_hours": [1264],
        "filter_hours": [420],
        "serial_number": "SMILESIM2026032901",
        "software_version": "2.0.7-sim",
        "input_resolution": "1920x1080",
        "recommended_resolution": "1920x1080",
        "error_status": "000000",
    },
    "appotronics_2_0": {
        "id": "appotronics_2_0",
        "name": "Appotronics 2.0",
        "brand": "Appotronics",
        "pjlink_class": 2,
        "default_auth_mode": "md5",
        "power_on_delay": 3.0,
        "power_off_delay": 2.5,
        "supports": {
            "freeze": True,
            "speaker_volume": True,
            "microphone_volume": False,
            "input_name": True,
            "input_resolution": True,
            "recommended_resolution": True,
            "filter_hours": False,
            "lamp_model": True,
            "filter_model": False,
            "serial_number": True,
            "software_version": True,
        },
        "inputs": {
            "11": "VGA 1",
            "31": "HDMI 1",
            "32": "DVI",
            "33": "HDMI 2",
            "51": "Network",
        },
        "manufacturer_name": "APPOTRONICS",
        "product_name": "DH Series Simulator",
        "device_name": "APPOTRONICS-SIM",
        "other_info": "Class 2 profile tuned for Guangfeng/Appotronics testing",
        "lamp_models": ["ALPD-LASER-01"],
        "filter_models": [],
        "lamp_hours": [2389],
        "filter_hours": [],
        "serial_number": "APTSIM2026032901",
        "software_version": "2.3.1-sim",
        "input_resolution": "3840x2160",
        "recommended_resolution": "3840x2160",
        "error_status": "000000",
    },
}


def list_profiles() -> list[dict]:
    return [deepcopy(PROFILES[key]) for key in sorted(PROFILES)]


def get_profile(profile_id: str) -> dict:
    if profile_id not in PROFILES:
        raise KeyError(f"Unknown profile: {profile_id}")
    return deepcopy(PROFILES[profile_id])
